# Generated by Django 5.0.3 on 2024-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionattempt',
            name='unique_attempt_question',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionattempt',
            old_name='attempt_id',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='questionattempt',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question'),
        ),
    ]
